services:
  front:
    build:
      context: './client'
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    container_name: QueryQuest-client-container
    networks:
      - QueryQuest-network
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - backend
  
  backend:
    build:
      context: './server'
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    container_name: QueryQuest-server-container
    networks:
      - QueryQuest-network
    volumes:
     - ./server:/app
     - /app/node_modules
    depends_on:
      - mongo 

  mongo:
    image: mongo
    ports:
      - 27017:27017
    container_name: mongo-container
    networks:
      - QueryQuest-network
    volumes:
      - mongoData:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=qwerty
      - MONGO_INITDB_DATABASE=QueryQuest

networks:
  QueryQuest-network:
volumes:
  mongoData: